# Generated by Django 4.1.7 on 2023-04-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('news_app', '0007_alter_user_username'), ('news_app', '0008_alter_user_password'), ('news_app', '0009_alter_user_password')]

    dependencies = [
        ('news_app', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
