# Generated by Django 4.1.7 on 2023-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_user_username_squashed_0009_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/default_user.png', upload_to='img/'),
        ),
    ]
