# Generated by Django 4.1.7 on 2023-04-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('news_app', '0011_user_avatar_alter_post_image'), ('news_app', '0012_alter_post_image_alter_user_avatar')]

    dependencies = [
        ('news_app', '0010_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/default_post.png', upload_to='img/posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='img/posts/default_post.png', upload_to='img/posts/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/users/default_user.png', upload_to='img/users/'),
        ),
    ]
